# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1394720846);
user_pref("app.update.lastUpdateTime.background-update-timer", 1394721086);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1394720966);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1394797939);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.lastAppVersion", "1.0pre (Debian-1.0~~pre+git1401172307-~nightly1)");
user_pref("extensions.lastPlatformVersion", "23.0");
user_pref("extensions.shownSelectionUI", true);
user_pref("idle.lastDailyNotification", 1394723910);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1394723911);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.importedState", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1392900681);
user_pref("toolkit.telemetry.previousBuildID", "root@jumper_1390000078");
