{:user {:plugins [[lein-pprint "1.1.1"]
                  [com.cemerick/pomegranate "0.3.0"]
                  [lein-exec "0.3.5"]
                  [lein-midje "3.1.3"]
                  [lein-newnew "0.2.6"]
                  [lein-noir "1.1.0"]
                  [lein-clojars "0.8.0"]
                  [lein-git-version "0.0.6"]
                  [lein-webrepl "0.1.0-SNAPSHOT"]
                  [com.novemberain/monger "2.0.0"]
                  [lein-kibit "RELEASE"]
                  [clj-growl "0.2.1"]
                  [cider/cider-nrepl "0.13.0"]
                  [org.julienxx/clj-slack "0.5.1"]
                  [clj-http "2.3.0"]
                  [cheshire "5.10.2"]
                  [etaoin "0.4.6"]
                  [clj-time "0.14.2"]
                  [lein-marginalia "0.7.1"]]
        :dependencies [[org.clojure/tools.trace "RELEASE"]
                       [org.clojure/tools.nrepl "0.2.11"]
                       [com.palletops/pallet "0.8.12"]]}}
