{ title: "見積書",
  created_on: "2021年5⽉24⽇",
  no: "2021-0524-0008",
  subject: "ID: 12345の見積り",
  expired_on: "2021年6⽉24⽇",
  from: {
    company_name: "有限会社丸芳製作所",
    representation_name: "関根芳之",
    zip_code: "223-0052",
    address: "神奈川県横浜市港北区綱島東5-4-26",
    tel: "0455421131",
    stamp: false
  },
  to: "仁科建設株式会社",
  body: [{ name: "FM-A",
           count: 1,
           price: 13000,
         },
         { name: "FM-B",
           count: 1,
           price: 11000,
         },
         { name: "FM-C",
           count: 1,
           price: 9500,
         },
         { name: "FM-D",
           count: 1,
           price: 5000,
         },
         { name: "FM-E",
           count: 1,
           price: 13000,
         },
         { name: "FM-F",
           count: 1,
           price: 4500,
         },
         { name: "FM-G",
           count: 1,
           price: 7500,
         },
         { name: "FM-H",
           count: 1,
           price: 10000,
         },
         { name: "FM-I",
           count: 1,
           price: 2600,
         },
        ],
  tax_included: false,
  note: ""
}
